## Spotify Data Cleaning and Preparation using Python

### **Objective:** 
This notebook focuses on preparing the Spotify dataset for analysis. The goal is to clean the data by removing invalid records and fixing text inconsistencies so that it can be used for SQL-based analysis.

In [27]:
# Import libraries

import pandas as pd
import numpy as np

### Loading the dataset to inspect its structure and understand the available columns.

In [28]:
# Load the dataset

data=pd.read_csv('spotify_dataset.csv')

### Checking column names, data types, and sample rows to understand data quality.

In [29]:
data.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  object
 2   artists           113999 non-null  object
 3   album_name        113999 non-null  object
 4   track_name        113999 non-null  object
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(6), object(5)
memory usage: 17.5+ MB

In [31]:
print(data.columns.tolist())

['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name', 'popularity', 'duration_ms', 'explicit', 'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature', 'track_genre']

### Data Cleaning Steps

1. **Change datatypes**  
   Ensure each column has the correct format for accurate analysis.

2. **Remove unwanted columns**  
   Eliminate unnecessary data to simplify processing and improve performance.

3. **Remove null values**  
   Avoid missing data issues that can affect calculations and insights.

4. **Remove outliers**  
   Prevent extreme values from distorting analysis results.

5. **Remove duplicates**  
   Ensure each record is unique to maintain data accuracy.

6. **Remove whitespaces**  
   Clean text fields to avoid inconsistencies and matching errors.

7. **Modify rows for better processing**  
   Standardize data to make it easier for analysis and querying.

In [32]:
# Change Boolean datatype to int

data['explicit']=data['explicit'].astype(int)

In [33]:
# Remove unwanted columns

data.drop('Unnamed: 0',axis=1,inplace=True)

In [34]:
# Check for null

data.isnull().sum()

track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [35]:
# Drop null values

data.dropna(axis=0,inplace=True)

In [36]:
# Check for duplicates

data.duplicated().sum()

450

In [37]:
# Remove duplicates

data.drop_duplicates(ignore_index=True, inplace=True)

In [38]:
# Rename column for better readability

data.rename({'artists':'artist_name','key':'track_key','mode':'track_mode'},axis=1,inplace=True)

In [39]:
# Text cleanup

data['track_name'] = data['track_name'].str.strip()
data['album_name'] = data['album_name'].str.strip()
data['artist_name'] = data['artist_name'].str.strip()

In [40]:
# check for outliers
# danceability, energy, mode, speechiness,acousticness, explicit, instrumentalness, 
# liveness, valance all have values only between 0 and 1

data.describe()

,popularity,duration_ms,explicit,danceability,energy,track_key,loudness,track_mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,113549.000000,1.135490e+05,113549.000000,113549.000000,113549.000000,113549.000000,113549.000000,113549.000000,113549.000000,113549.000000,113549.000000,113549.000000,113549.000000,113549.000000,113549.000000
mean,33.324433,2.280814e+05,0.085584,0.567031,0.642091,5.309452,-8.243408,0.637866,0.084674,0.314064,0.155703,0.213613,0.474205,122.175745,3.904218
std,22.283855,1.064131e+05,0.279750,0.173409,0.251053,3.560147,5.011422,0.480620,0.105762,0.331906,0.309217,0.190462,0.259204,29.972954,0.432117
min,0.000000,8.586000e+03,0.000000,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,17.000000,1.741840e+05,0.000000,0.456000,0.473000,2.000000,-9.998000,0.000000,0.035900,0.016800,0.000000,0.098000,0.260000,99.296000,4.000000
50%,35.000000,2.130000e+05,0.000000,0.580000,0.685000,5.000000,-6.997000,1.000000,0.048900,0.168000,0.000041,0.132000,0.464000,122.020000,4.000000
75%,50.000000,2.615880e+05,0.000000,0.695000,0.854000,8.000000,-5.001000,1.000000,0.084500,0.596000,0.048700,0.273000,0.683000,140.074000,4.000000
max,100.000000,5.237295e+06,1.000000,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [41]:
# Change duration from ms to mins

data['duration_mins']=(data['duration_ms']/60000).round(1)

In [42]:
# Make all clumn_names small letter for better sql query execution

data.columns = data.columns.str.lower()

In [43]:
# Clean column names by removing whitespaces

data.columns = data.columns.str.strip()

In [44]:
# Ensure track_id is string before using .str

data['track_id'] = data['track_id'].astype(str)

In [45]:
# Remove bad rows (very long corrupted ones)

data = data[data['track_id'].str.len() < 50]

In [46]:
# Remove line breaks inside data

data = data.replace({r'\n': ' ', r'\r': ' '}, regex=True)

In [47]:
# Drop completely empty rows

data = data.dropna(how='all')

In [48]:
# Final Check

data.info()
data.isnull().sum()
data.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113549 entries, 0 to 113548
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   track_id          113549 non-null  object
 1   artist_name       113549 non-null  object
 2   album_name        113549 non-null  object
 3   track_name        113549 non-null  object
 4   popularity        113549 non-null  int64
 5   duration_ms       113549 non-null  int64
 6   explicit          113549 non-null  int32
 7   danceability      113549 non-null  float64
 8   energy            113549 non-null  float64
 9   track_key         113549 non-null  int64
 10  loudness          113549 non-null  float64
 11  track_mode        113549 non-null  int64
 12  speechiness       113549 non-null  float64
 13  acousticness      113549 non-null  float64
 14  instrumentalness  113549 non-null  float64
 15  liveness          113549 non-null  float64
 16  valence           113549 non-null  float64
 17  tempo             113549 non-null  float64
 18  time_signature    113549 non-null  int64
 19  track_genre       113549 non-null  object
 20  duration_mins     113549 non-null  float64
dtypes: float64(10), int32(1), int64(5), object(5)
memory usage: 17.8+ MB

0

### Exporting the cleaned dataset for further analysis in SQL.

In [49]:
# Save clean file
data.to_csv("spotify_final_clean.csv", index=False)

### **Conclusion:**
The dataset has been cleaned by removing invalid rows and fixing text inconsistencies. The final dataset is now structured and ready for SQL-based analysis.